spring.application.name=HospitalAppointment

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:h2:mem:hospitaldb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.secret=${JWT_SECRET:change-this-secret-key-to-a-long-random-value-change-this-secret-key}
app.security.jwt.access-token-expiration-minutes=${JWT_ACCESS_EXP_MIN:15}
app.security.jwt.refresh-token-expiration-days=${JWT_REFRESH_EXP_DAYS:7}

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
